# -- Dimensioni Arena -- #

W_ARENA = 500
H_ARENA = 350

# -- DIMENSIONI TERRENO -- #
X_LAND = 0
Y_LAND = 514
W_LAND = 509
H_LAND = 124

# -- VELOCITA -- #                                                
SPEED_LAND = 2
SPEED_MOUNTAIN = 0.5
SPEED_BLUE_MOUNTAIN = 0.1
SPEED = 5
SPEED_BULLET = 5
SPEED_BULLET_ENEMIES = 3

# -- DIMENSIONI MONTAGNA -- #

X_MOUNTAIN = 0
Y_MOUNTAIN = 257
W_MOUNTAIN = 509
H_MOUNTAIN = 124
HIGH_MOUNTAIN = 90

# -- DIMENSIONI MONTAGNA BLU -- #

X_BLUE_MOUNTAIN = 0
Y_BLUE_MOUNTAIN = 0
H_BLUE_MOUNTAIN = 207
W_BLUE_MOUNTAIN = 511

# -- ROVER -- #

W_ROVER = 36
H_ROVER = 27
POINTS_FOR_ROVER = 1
ROVER_UP = "UP"
ROVER_DOWN = "DOWN"
ROVER_NULL = "NULL"

# -- ROVER NORMALE -- #

X_CAR = 209
Y_CAR = 155

# -- ROVER UP -- #

X_CAR_UP = 43
Y_CAR_UP = 100

# -- ROVER DOWN -- #

X_CAR_DOWN = 78
Y_CAR_DOWN = 101

# -- BUCA -- #

X_HOLE = 135
Y_HOLE = 135
W_HOLE = 18
H_HOLE = 18
MIN_RANGE_TYPE_HOLE = 0
MAX_RANGE_TYPE_HOLE = 10
MIN_SPAWN_RATE_HOLE = 300
MAX_SPAWN_RATE_HOLE = 400
SPAWN_RATE_HOLE = 2

# -- BUCA MAGGIORE -- #

X_HOLE_BIGGER = 150
Y_HOLE_BIGGER = 135
W_HOLE_BIGGER = 32
H_HOLE_BIGGER = 32

# -- ALIENO -- #

X_ALIEN = 160
Y_ALIEN = 243
W_ALIEN = 29
H_ALIEN = 18
X_ALIEN_2 = 66
Y_ALIEN_2 = 227
W_ALIEN_2 = 16
H_ALIEN_2 = 14
ATTACK_RATE_ALIEN = 3
MIN_RANGE_TYPE_ALIEN = 0
MAX_RANGE_TYPE_ALIEN = 10
MIN_RANGE_ATTACK_ALIEN = 300
MAX_RANGE_ATTACK_ALIEN = 400
MAX_N_ALIEN = 3
POS_ALIEN = 50
MOVEMENT_ALIEN_X = 0
MOVEMENT_ALIEN_Y = 700

# -- ROCCIA -- #

X_ROCK = 75
Y_ROCK = 195
W_ROCK = 20
H_ROCK = 20
MIN_RANGE_TYPE_ROCK = 0
MAX_RANGE_TYPE_ROCK = 10
MAX_HITTED_TIMES_ROCK = 2
MIN_SPAWN_RATE_ROCK = 400
MAX_SPAWN_RATE_ROCK = 500
SPAWN_RATE_ROCK = 2

# -- ROCCIA MAGGIORE -- #

X_ROCK_BIGGER = 108
Y_ROCK_BIGGER = 193
W_ROCK_BIGGER = 20
H_ROCK_BIGGER = 20

# -- MOSTRO -- #

X_MONSTER = 105
Y_MONSTER = 242
W_MONSTER = 24
H_MONSTER = 20
ATTACK_RATE_MONSTER = 3
MIN_RANGE_ATTACK_MONSTER = 200
MAX_RANGE_ATTACK_MONSTER = 300
HITTED_MONSTER = 1
MAX_LIFE_MONSTER = 10

# -- PROIETTILE -- #

X_BULLET = 187
Y_BULLET = 137
W_BULLET = 18
H_BULLET = 11
BULLET_RIGHT = "RIGHT"
BULLET_UP = "UP"
BULLET_DOWN = "DOWN"
BULLET_LEFT = "LEFT"
RANGE_CREATE_HOLE1 = 0
RANGE_CREATE_HOLE2 = 20

# -- Constanti Gioco -- #

FPS = 120
G = 0.15
SPAWN_MIN_RANDOM_RANGE = 300
SPAWN_MAX_RANDOM_RANGE = 600
X_POINTS = 0
Y_POINTS = 320
DIM_POINTS = 15
X_TIME = 0
Y_TIME = 300
DIM_TIME = 15
DEFAULT_MINS = 0
DEFAULT_SECS = 30
POINTS = 10
WIN = "YOU WON with: "
LOSE = "YOU LOST with: "
ARROW_UP = "ArrowUp"
ARROW_RIGHT = "ArrowRight"
ARROW_LEFT = "ArrowLeft"
SPACE_BAR = "Spacebar"
SPRITES_CAR = "https://tomamic.github.io/images/sprites/moon-patrol.png"
SPRITES_LAND = "https://tomamic.github.io/images/sprites/moon-patrol-bg.png"